### ISSUE TITLE
Race condition on join lobby

### ISSUE THREAD

**Issue by TronPaul** [TronPaul/lobbypy#9]
When a player clicks join sometimes they do not see themselves listed as part of the lobby and the lobby never updates to show them in it.  Race condition between the ajax lobby state call and the socket.io join call.

**Comment by bcahue** [comment]
I'm leaning towards using Socket.IO's own socket.on() function in LobbiesNamespace.listener instead of a message loop to parse the join/leave/update events as events instead of messages, however, ready events (and calling an update when ready) may be unavoidable.

Edit: Oh you're using redis, I am blind.

**Comment by TronPaul** [comment]
FIxed by not using ajax
